# Laboratorium 4 — NumPy zaawansowane
**Autor:** Natalia Kania

## Ćwiczenie 1: Broadcasting — zastosowania biznesowe

In [13]:
import numpy as np

In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


In [7]:
# Zadanie 1a: zwiększenie cen o 5% (inflacja)
ceny_inflacja = ceny * 1.05
print(ceny_inflacja)
# Broadcasting: każda wartość w macierzy mnożona przez skalar 1.05

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


In [ ]:
# Zadanie 1b: ceny po rabatach
rabaty = np.array([0.10, 0.05, 0.15])

ceny_rabat = ceny * (1 - rabaty)
print(ceny_rabat)
# Broadcasting: wektor rabatów (3,) dopasowuje się do kolumn (3 sklepy)

[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


In [ ]:
# Zadanie 1c: koszt zakupu produktów
marza = np.array([[0.30], [0.40], [0.25], [0.50]])

koszt_zakupu = ceny / (1 + marza)
print(koszt_zakupu)
# Broadcasting: wektor kolumnowy (4x1) dopasowuje się do wierszy (produkty)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


In [ ]:
# Zadanie 1d: najtańszy sklep dla każdego produktu
indeksy = ceny.argmin(axis=1)

najtansze_sklepy = [sklepy[i] for i in indeksy]
print(najtansze_sklepy)
# argmin(axis=1) zwraca indeks najtańszego sklepu dla każdego produktu

['Online', 'Online', 'Online', 'Online']


## Ćwiczenie 2: Reshape i łączenie danych

In [8]:
# Dane miesięczne z jednego roku
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

# Reshape: 4 kwartały × 3 miesiące
kwartaly = dane_flat.reshape(4, 3)

print("Kwartały:\n", kwartaly)

# suma w każdym wierszu (czyli kwartale)
suma_kw = kwartaly.sum(axis=1)
print("Suma per kwartał:", suma_kw)

# indeks najlepszego kwartału (+1 bo indeksy od 0)
print("Najlepszy kwartał: Q", suma_kw.argmax() + 1)

Kwartały:
 [[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q 4


In [9]:
# Dane oddziałów
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])

# vstack: łączenie w pionie (wiersze)
wszystkie = np.vstack([warszawa, krakow, wroclaw])

print("Wszystkie:\n", wszystkie)

# suma per oddział (wiersze)
print("Suma per oddział:", wszystkie.sum(axis=1))

# suma per kwartał (kolumny)
print("Suma per kwartał:", wszystkie.sum(axis=0))

Wszystkie:
 [[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


In [10]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])

# 1. reshape na 6×2 (6 produktów, 2 miesiące)
sprzedaz = sprzedaz_flat.reshape(6, 2)

# 2. średnia per produkt (wiersze)
srednia = sprzedaz.mean(axis=1)
print("Średnia:", srednia)

# 3. zmiana miesiąc 2 - miesiąc 1
zmiana = sprzedaz[:, 1] - sprzedaz[:, 0]
print("Zmiana:", zmiana)

Średnia: [150. 225. 215. 170. 240. 225.]
Zmiana: [100 150 -70 100 140 -70]


In [11]:
# 1. spłaszczenie macierzy kwartaly
flat = kwartaly.flatten()

# 2. dodanie 13 miesiąca
nowe_dane = np.concatenate([flat, np.array([235])])

print(nowe_dane)
print("Długość:", len(nowe_dane))

[120 135  98 142 167 189 201 178 156 143 198 221 235]
Długość: 13


## Ćwiczenie 3: Analiza danych finansowych

In [14]:
##Dane
np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

In [15]:
# 1. statystyki podstawowe
srednia = pensje.mean()
mediana = np.median(pensje)
odchylenie = pensje.std()

print("Średnia:", srednia)
print("Mediana:", mediana)
print("Odchylenie:", odchylenie)

# 2. osoby powyżej średniej
nazwy = np.array(pracownicy)
powyzej_sredniej = nazwy[pensje > srednia]
print("Powyżej średniej:", powyzej_sredniej)

# 3. osoby poniżej mediany
ponizej_mediany = nazwy[pensje < mediana]
print("Poniżej mediany:", ponizej_mediany)

# 4. rozstęp i IQR
rozstep = pensje.max() - pensje.min()
iqr = np.percentile(pensje, 75) - np.percentile(pensje, 25)

print("Rozstęp:", rozstep)
print("IQR:", iqr)

Średnia: 6425.0
Mediana: 6050.0
Odchylenie: 1616.9029037020127
Powyżej średniej: ['Jan' 'Marek' 'Zofia']
Poniżej mediany: ['Anna' 'Ewa' 'Piotr' 'Tomek']
Rozstęp: 4900
IQR: 2200.0


In [16]:
# przydział premii
premie = np.where(oceny >= 4.5, 2000,
         np.where(oceny >= 4.0, 1000, 0))

print("Premie:", premie)

# nowe wynagrodzenia
nowe_pensje = pensje + premie
print("Nowe pensje:", nowe_pensje)

# kto ma najwyższą premię
idx_max = premie.argmax()
print("Najwyższa premia:", nazwy[idx_max])

Premie: [1000    0 2000 1000 2000    0 1000    0]
Nowe pensje: [ 6500  7200  6800 10100  8300  4200  9500  5800]
Najwyższa premia: Ewa


In [17]:
# sortowanie malejąco
kolejnosc = np.argsort(pensje)[::-1]

# ranking
for i, idx in enumerate(kolejnosc, 1):
    print(i, nazwy[idx], pensje[idx], "staż:", staz[idx])

1 Marek 9100 staż: 15
2 Zofia 8500 staż: 12
3 Jan 7200 staż: 8
4 Kasia 6300 staż: 5
5 Tomek 5800 staż: 4
6 Anna 5500 staż: 3
7 Ewa 4800 staż: 2
8 Piotr 4200 staż: 1


In [18]:
# korelacje
korelacja_staz_pensje = np.corrcoef(staz, pensje)[0, 1]
korelacja_staz_oceny = np.corrcoef(staz, oceny)[0, 1]

print("Staż vs pensja:", korelacja_staz_pensje)
print("Staż vs oceny:", korelacja_staz_oceny)

Staż vs pensja: 0.987862864584301
Staż vs oceny: 0.04198471605953068


In [19]:
# poprawny broadcasting (4x6) * (4x1)
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

print("Przychód:\n", przychod)

# łączny przychód per produkt
suma_produkt = przychod.sum(axis=1)
najlepszy_produkt = produkty_nazwy[suma_produkt.argmax()]
print("Najlepszy produkt:", najlepszy_produkt)

# najlepszy miesiąc
suma_miesiac = przychod.sum(axis=0)
najlepszy_miesiac = suma_miesiac.argmax() + 1
print("Najlepszy miesiąc:", najlepszy_miesiac)

# trend: pierwsze 3 vs ostatnie 3 miesiące
pierwsze = przychod[:, :3].sum()
ostatnie = przychod[:, 3:].sum()

print("Pierwsze 3 mies.:", pierwsze)
print("Ostatnie 3 mies.:", ostatnie)

Przychód:
 [[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]
Najlepszy produkt: Smartfon
Najlepszy miesiąc: 2
Pierwsze 3 mies.: 2463950
Ostatnie 3 mies.: 2536500


## Ćwiczenie 4: Generowanie danych 

In [20]:
import numpy as np

np.random.seed(42)

wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

In [26]:
# Obliczenie podstawowych statystyk dla wieku
print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std: {wiek.std():.1f}, min: {wiek.min()}, max: {wiek.max()}")

# Obliczenie statystyk dla wydatków
print(f"Wydatki — średnia: {wydatki.mean():.1f}, mediana: {np.median(wydatki):.1f}, std: {wydatki.std():.1f}, min: {wydatki.min():.1f}, max: {wydatki.max():.1f}")

# Obliczenie statystyk dla liczby wizyt
print(f"Wizyty — średnia: {wizyty.mean():.1f}, mediana: {np.median(wizyty):.1f}, std: {wizyty.std():.1f}, min: {wizyty.min()}, max: {wizyty.max()}")

Wiek — średnia: 33.6, mediana: 33.0, std: 8.6, min: 18, max: 53
Wydatki — średnia: 504.5, mediana: 516.8, std: 189.8, min: 116.2, max: 1044.0
Wizyty — średnia: 4.9, mediana: 5.0, std: 2.2, min: 1, max: 11


In [27]:
# Obliczenie korelacji między wiekiem a wydatkami
korelacja_wiek = np.corrcoef(wiek, wydatki)[0, 1]
print("Korelacja wiek–wydatki:", korelacja_wiek)

Korelacja wiek–wydatki: -0.12009183441777695


In [28]:
# Obliczenie korelacji między liczbą wizyt a wydatkami
korelacja_wizyty = np.corrcoef(wizyty, wydatki)[0, 1]
print("Korelacja wizyty–wydatki:", korelacja_wizyty)

Korelacja wizyty–wydatki: -0.15884985147948125


In [29]:
# Obliczenie średniej i odchylenia standardowego wydatków
sr = wydatki.mean()
sd = wydatki.std()

# Segmentacja klientów na podstawie poziomu wydatków
segment = np.where(wydatki > sr + sd, 'WYSOKI',
          np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))

print(segment)

['NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'NISKI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI'
 'NISKI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI'
 'ŚREDNI' 'WYSOKI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'NISKI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'WYSOKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'WYSOKI' 'ŚREDNI' 'WYSOKI'
 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI' 'ŚREDNI' 'ŚREDNI'
 'ŚREDNI' 'ŚREDNI' 'ŚREDNI' 'NISKI']


In [30]:
# Zliczenie liczby klientów w każdym segmencie
unikalne, liczba = np.unique(segment, return_counts=True)

# Wyświetlenie wyników
for s, l in zip(unikalne, liczba):
    print(s, ":", l)

NISKI : 17
WYSOKI : 12
ŚREDNI : 71
