# Laboratorium 3 — NumPy
**Autor:** Natalia  
**Data:** 23.03.2026

# Ćwiczenie 1:

In [1]:
import numpy as np

In [2]:
# 1. Z listy
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")


Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


In [3]:
# 2. Zera — 10 elementów
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# 3. Jedynki — macierz 3×5
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")


Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [5]:
# 4. Sekwencja od 0 do 100, co 10
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")


Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


In [6]:
# 5. 7 równomiernych punktów od 0 do 1
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")


Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [7]:
# 6. 20 losowych ocen od 2 do 5
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")


Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


In [8]:
# Zbadaj tablicę losowych ocen
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


# Ćwiczenie 2:

# Część A — Tablica 1D

In [3]:
import numpy as np

miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])

In [4]:
# 1. Sprzedaż w styczniu (indeks 0)
print("Sprzedaż w styczniu:", miesiace_sprzedaz[0])

Sprzedaż w styczniu: 120


In [ ]:
# 2. Sprzedaż w grudniu (ostatni element)
print("Sprzedaż w grudniu:", miesiace_sprzedaz[-1])

Sprzedaż w grudniu: 221


In [6]:
# 3. Sprzedaż w Q1 (styczeń-marzec)
print("Sprzedaż w Q1:", miesiace_sprzedaz[0:3])

Sprzedaż w Q1: [120 135  98]


In [ ]:
# 4. Sprzedaż w Q4 (październik-grudzień)
print("Sprzedaż w Q4:", miesiace_sprzedaz[-3:])


Sprzedaż w Q4: [143 198 221]


In [8]:
# 5. Sprzedaż co drugi miesiąc (styczeń, marzec, maj…)
print("Sprzedaż co drugi miesiąc:", miesiace_sprzedaz[::2])


Sprzedaż co drugi miesiąc: [120  98 167 201 156 198]


In [9]:
# 6. Sprzedaż od tyłu (grudzień → styczeń)
print("Sprzedaż od tyłu:", miesiace_sprzedaz[::-1])

Sprzedaż od tyłu: [221 198 143 156 178 201 189 167 142  98 135 120]


# Część B — Macierz 2D

In [10]:
# Sprzedaż 4 produktów w 3 kwartałach
dane = np.array([
[120, 145, 167], # Produkt A
[89, 102, 95], # Produkt B
[234, 267, 289], # Produkt C
[56, 78, 91], # Produkt D
])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']

In [11]:
# 1. Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1)
print("Sprzedaż Produktu A w Q2:", dane[0, 1])

Sprzedaż Produktu A w Q2: 145


In [13]:
# 2. Cała sprzedaż Produktu C (wiersz 2)
print("Sprzedaż Produktu C:", dane[2, :])

Sprzedaż Produktu C: [234 267 289]


In [14]:
# 3. Sprzedaż wszystkich produktów w Q1 (kolumna 0)
print("Sprzedaż wszystkich produktów w Q1:", dane[:, 0])

Sprzedaż wszystkich produktów w Q1: [120  89 234  56]


In [16]:
# 4. Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2)
print("Sprzedaż Produktów B i C w Q2 i Q3:", dane[1:3, 1:3])

Sprzedaż Produktów B i C w Q2 i Q3: [[102  95]
 [267 289]]


# Ćwiczenie 3:

In [17]:
# Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

## Zadanie 1: Podstawowe statystyki cenowe
Średnia cena, najdroższy i najtańszy produkt

In [ ]:
# Zadanie 1: Podstawowe statystyki cenowe

# Średnia cena
srednia_cena = ceny.mean()
# Najdroższy produkt
najdrozszy_ind = ceny.argmax()
najdrozszy = nazwy[najdrozszy_ind]
# Najtańszy produkt
najtanszy_ind = ceny.argmin()
najtanszy = nazwy[najtanszy_ind]

print(f"Średnia cena: {srednia_cena} zł")
print(f"Najdroższy produkt: {najdrozszy} ({ceny[najdrozszy_ind]} zł)")
print(f"Najtańszy produkt: {najtanszy} ({ceny[najtanszy_ind]} zł)")

Średnia cena: 1171.0 zł
Najdroższy produkt: Laptop (3499 zł)
Najtańszy produkt: Ładowarka (89 zł)


## Zadanie 2: Wartość magazynu
Oblicz wartość każdego produktu i łączną wartość magazynu

In [ ]:
# Zadanie 2: wartość magazynu
 
# Wartość każdego produktu
wartosc_produktow = ceny * ilosci_magazyn

# Tworzymy słownik: nazwa -> wartość
slownik_wartosci = dict(zip(nazwy, wartosc_produktow))

# Łączna wartość magazynu
laczna_wartosc = wartosc_produktow.sum()

# Wypisanie wartości każdego produktu
print("Wartość magazynowa poszczególnych produktów:")
for produkt, wartosc in slownik_wartosci.items():
    print(f"{produkt}: {wartosc} zł")

# Wypisanie łącznej wartości
print(f"\nŁączna wartość magazynu: {laczna_wartosc} zł")

Wartość magazynowa poszczególnych produktów:
Laptop: 52485 zł
Tablet: 79758 zł
Smartfon: 194922 zł
Słuchawki: 54444 zł
Ładowarka: 27768 zł
Klawiatura: 22161 zł
Mysz: 25929 zł
Monitor: 34477 zł
Kamera: 26955 zł
Drukarka: 30566 zł

Łączna wartość magazynu: 549465 zł


## Zadanie 3: Analiza cenowa
Stwórz array z cenami po rabacie 15% (promocja świąteczna) oraz z uwzględnieniem VAT 23%.  
Policz, ile produktów kosztuje powyżej 1000 zł po rabacie.

In [23]:
# Zadanie 3: Analiza cenowa
rabat = ceny * 0.85
vat = ceny * 1.23

# Ile produktów kosztuje powyżej 1000 zł po rabacie?
liczba_pow_1000 = (rabat > 1000).sum()

print("Ceny po rabacie 15%:", rabat)
print("Ceny po uwzględnieniu VAT 23%:", vat)
print(f"Liczba produktów po rabacie > 1000 zł: {liczba_pow_1000}")

Ceny po rabacie 15%: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny po uwzględnieniu VAT 23%: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
Liczba produktów po rabacie > 1000 zł: 4


## Zadanie 4: Filtrowanie
Znajdź produkty:  
- z oceną >= 4.5 — wyświetl nazwy i ceny  
- poniżej 200 zł — wyświetl nazwy i ilości w magazynie

In [24]:
# Zadanie 4: Filtrowanie
nazwy_array = np.array(nazwy)

# Produkty z oceną >= 4.5
mask_4_5 = oceny_klientow >= 4.5
print("Produkty z oceną >= 4.5:")
for n, c in zip(nazwy_array[mask_4_5], ceny[mask_4_5]):
    print(f"{n}: {c} zł")

# Produkty poniżej 200 zł
mask_200 = ceny < 200
print("\nProdukty < 200 zł i ilość w magazynie:")
for n, il in zip(nazwy_array[mask_200], ilosci_magazyn[mask_200]):
    print(f"{n}: {il} szt.")

Produkty z oceną >= 4.5:
Laptop: 3499 zł
Smartfon: 2499 zł
Słuchawki: 349 zł
Monitor: 1499 zł

Produkty < 200 zł i ilość w magazynie:
Ładowarka: 312 szt.
Mysz: 201 szt.


## Zadanie 5: Analiza zapasów
Wyświetl produkty z niskim stanem magazynowym (<30 szt.),  
oblicz ich łączną wartość i procent całego magazynu.

In [25]:
# Zadanie 5: Analiza zapasów
mask_niski = ilosci_magazyn < 30
wartosci_niskie = (ceny * ilosci_magazyn)[mask_niski]
suma_niskie = wartosci_niskie.sum()
procent_magazynu = suma_niskie / (ceny * ilosci_magazyn).sum() * 100

print("Produkty z niskim stanem magazynowym (<30 szt.):")
for n in nazwy_array[mask_niski]:
    print(n)
print(f"Łączna wartość tych produktów: {suma_niskie} zł")
print(f"Procent całego magazynu: {procent_magazynu:.2f}%")

Produkty z niskim stanem magazynowym (<30 szt.):
Laptop
Monitor
Łączna wartość tych produktów: 86962 zł
Procent całego magazynu: 15.83%


## Zadanie 6 (bonus): Analiza korelacji cena–ocena
- Które produkty są "okazją" — ocena >= 4.5 i cena < 1000 zł?  
- Jaka jest średnia cena produktów z oceną >= 4.0 vs < 4.0?

In [26]:
# Zadanie 6 (bonus): Analiza korelacji cena–ocena
mask_okazje = (oceny_klientow >= 4.5) & (ceny < 1000)
print("Produkty 'okazja' (ocena >= 4.5 i cena < 1000 zł):")
for n, c in zip(nazwy_array[mask_okazje], ceny[mask_okazje]):
    print(f"{n}: {c} zł")

# Średnia cena produktów ocena >=4.0 vs <4.0
mask_ge4 = oceny_klientow >= 4.0
mask_lt4 = oceny_klientow < 4.0
srednia_ge4 = ceny[mask_ge4].mean()
srednia_lt4 = ceny[mask_lt4].mean()

print(f"\nŚrednia cena produktów z oceną >= 4.0: {srednia_ge4:.2f} zł")
print(f"Średnia cena produktów z oceną < 4.0: {srednia_lt4:.2f} zł")

Produkty 'okazja' (ocena >= 4.5 i cena < 1000 zł):
Słuchawki: 349 zł

Średnia cena produktów z oceną >= 4.0: 1446.14 zł
Średnia cena produktów z oceną < 4.0: 529.00 zł


## Ćwiczenie 4:

In [27]:
import numpy as np
import time

# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)

# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start

print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 78.3 ms
NumPy: 2.8 ms
NumPy jest 28× szybszy!


In [28]:
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start

start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start

print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Suma (1,000,000 elementów) ===
Lista: 7.2 ms
NumPy: 1.3 ms
NumPy jest 6× szybszy!


In [29]:
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start

start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start

print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")


=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 61.8 ms
NumPy: 4.2 ms
NumPy jest 15× szybszy!


## Wnioski z benchmarku
- NumPy jest **28×** szybszy w mnożeniu  
- NumPy jest **6×** szybszy w sumowaniu  
- NumPy jest **15×** szybszy w filtrowaniu  

**Wniosek:** przy dużych danych **zawsze** używaj NumPy zamiast list.